#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

dist: xenial
addons:
  apt:
    packages:
    - doxygen
    - doxygen-latex
    - libboost-all-dev
    - libeigen3-dev
    - python-pip
    - python3-pip
    - cython
    - python-nose
    - python-numpy
    - python-coverage
    - cython3
    - python3-nose
    - python3-numpy
    - python3-coverage
    - python3-setuptools
    - gfortran
branches:
  except:
    - debian
language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES=""
  - GIT_DEPENDENCIES="jrl-umi3218/Eigen3ToPython jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn jrl-umi3218/eigen-qld jrl-umi3218/sch-core jrl-umi3218/sch-core-python"
  - DEBSIGN_KEYID=5AE5CD75
  - GH_USERNAME=gergondet
  - GH_REPO=jrl-umi3218/Tasks
  - secure: sGswEcmMXNjod4m7F2ISsOsW8lM5EJckRp/SqkzdpAKDZl9W2zBoitMi/8FR3KGbpMsHHVP5SCa3+x3djDh3YXqZwxQm/+upqKWDFVXusdR+W/Xy0IncnRO2ADyCtfvb3Phc9TAvKey7GNP2bWTFC0/W0gQcrvT2feDlgWDXm6c=
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON -DPYTHON_BINDING_USER_INSTALL:BOOL=ON"
  matrix:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
    - CMAKE_BUILD_TYPE=Debug
notifications:
  slack:
    secure: kjUy0ltOahScMXln4/rjXG7fg/7G3l9D2M8Nd1b2GDsAfGvf8xhSFTwlXwlI4sr/Kr/9aP7/c1fjEucnR2bP4Z00G6ywRLhC7XPGAYNJ7AOGN9asX/fQZ/NXs9ADs6mTuGExvBaT/Xb6HYKi+4OIqtUhAtGK/HafVacVHlfl8RM=
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
- export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
- ./.travis/run  before_install
